spring.application.name=back

# -----------------------------------------------------------------------------
# Configuration Database Neon (PostgreSQL Cloud via .env)
# -----------------------------------------------------------------------------
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Désactivé pour ne pas chevaucher PostgreSQL localement
spring.docker.compose.enabled=false

# Configuration Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Application Properties Personnalisées (Pour notre futur service JWT)
application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250655368566D5970
# Expiration du token : 1 jour (en millisecondes)
application.security.jwt.expiration=86400000

spring.docker.compose.enabled=true 

# Configuration SMTP Brevo (Via variables d'environnement)
spring.mail.host=${SMTP_HOST:smtp-relay.brevo.com}
spring.mail.port=${SMTP_PORT:587}
spring.mail.username=${SMTP_USERNAME}
spring.mail.password=${SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Ignorer la vérification stricte du certificat SSL
spring.mail.properties.mail.smtp.ssl.trust=${SMTP_HOST:smtp-relay.brevo.com}

# Email de l'expéditeur par défaut
app.mail.from=${MAIL_FROM}
