spring.application.name=back

# Configuration Database PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/backbrainbooster
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuration Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Application Properties Personnalisées (Pour notre futur service JWT)
application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250655368566D5970
# Expiration du token : 1 jour (en millisecondes)
application.security.jwt.expiration=86400000

spring.docker.compose.enabled=true 

# Configuration SMTP Brevo (Sendinblue)
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=b2034e001@smtp-brevo.com
spring.mail.password=${SMTP_PASSWORD:votre_cle_ici}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Ignorer la vérification stricte du certificat SSL pour Brevo
spring.mail.properties.mail.smtp.ssl.trust=smtp-relay.brevo.com

# Email de l'expéditeur par défaut 
app.mail.from=dountiojoel24@gmail.com

spring.docker.compose.enabled=false
