spring.application.name=back
# Configuration Database PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/backbrainbooster
spring.datasource.username=dipita
spring.datasource.password=motdepasse123
spring.datasource.driver-class-name=org.postgresql.Driver
# Configuration Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Application Properties Personnalisées (Pour notre futur service JWT)
application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250655368566D5970
# Expiration du token : 1 jour (en millisecondes)
application.security.jwt.expiration=86400000
spring.docker.compose.enabled=true